### ISSUE TITLE
Memory leaks inside docker

### ISSUE THREAD

**Issue by trimon90** [WPO-Foundation/wptagent#331]
Running agent this way:

```
  wpt_agent:
    image: webpagetest/agent:release
#    init: true
    shm_size: 2G
    network_mode: "host"
    ports:
      - 81:80
    environment:
      SERVER_URL: http://localhost:80/work/
      LOCATION: Linux
      CONNECT_TIME_LIMIT: 120
      EXTRA_ARGS: "-m debug --checknet yes --log /debug.log "
      SHAPER: none
    depends_on:
      - wpt_server
    cap_add:
      - NET_ADMIN
    privileged: true
```
After each test we observe a memory leak (with chrome about 80-90 mb, less with firefox) and none zombies. It seems like python proccess grows in VSZ and RSS. Restarting the container is not an acceptable way out of this for us. Is any proper way to fix it?
