### ISSUE TITLE
Docker: Resetting dropped connection: ***

### ISSUE THREAD

**Issue by bushev** [WPO-Foundation/wptagent#377]
Hello,

I'm trying to spin up a very simple server + agent configuration, locally on macOS.

My docker-compose.jml file is:

```
version: '3.7'

services:

  webpagetest_server:
    container_name: webpagetest_server
    image: webpagetest/server
    privileged: true
    restart: always
    ports:
      - '0.0.0.0:7777:80'

  webpagetest_agent:
    container_name: webpagetest_agent
    image: webpagetest/agent
    environment:
      SERVER_URL: 'http://192.168.1.188:7777/work/' # Laptop WiFi address
      LOCATION: 'Test_loc'
      EXTRA_ARGS: '-vvvv'
      NAME: 'Test'
    cap_add:
      - NET_ADMIN
    privileged: true
    depends_on:
      - webpagetest_server
    init: true
    restart: always
    network_mode: host
    ports:
      - '0.0.0.0:9999:8888'
```

For some reason, the agent is unable to connect to the server (No agents connected).

Logs: [log.txt](https://github.com/WPO-Foundation/wptagent/files/5127555/log.txt)

Could you please give me some advice? Is the Docker install up-to-date?

When I'm trying to open exactly the same URL in a browser, I got 200 with an empty response body.

![image](https://user-images.githubusercontent.com/7535766/91253568-1f6d7380-e72e-11ea-9daa-d708098bb07c.png)

![image](https://user-images.githubusercontent.com/7535766/91254315-0d8cd000-e730-11ea-8e83-4fd48e45d35e.png)

![image](https://user-images.githubusercontent.com/7535766/91254506-960b7080-e730-11ea-8d93-467047a7fd4e.png)
